In [1]:
import tensorflow as tf

In [6]:
tensor_zero_d = tf.constant(5) # 0 dimentional tensor 

In [7]:
print(tensor_0_d)

tf.Tensor(5, shape=(), dtype=int32)


In [9]:
tensor_one_d=tf.constant([1,2,3,4,5])

In [10]:
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [11]:
tensor_2_d = tf.constant([[12,3,4,4],[20,80,100,11]])

In [12]:
print(tensor_2_d)

tf.Tensor(
[[ 12   3   4   4]
 [ 20  80 100  11]], shape=(2, 4), dtype=int32)


In [13]:
tensor_3_d = tf.constant([
    [[1,1],[2,2]],
    [[1,1],[2,2]],
])

In [14]:
print(tensor_3_d)

tf.Tensor(
[[[1 1]
  [2 2]]

 [[1 1]
  [2 2]]], shape=(2, 2, 2), dtype=int32)


In [16]:
tensor_string= tf.constant('Hello Zeeshan')

In [17]:
print(tensor_string)

tf.Tensor(b'Hello Zeeshan', shape=(), dtype=string)


In [18]:
tensor_bool= tf.constant([True,True,False])

In [19]:
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [20]:
import numpy as np 

In [21]:
arr= np.array([1,3,4])

In [23]:
converted_to_tensor=tf.convert_to_tensor(arr)

In [24]:
print(converted_to_tensor)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)
